# Data Arguments
DataArguments:
  name: jinmang2/load_klue_re
  revision: v1.0.0
  data_cache_dir: cache
  collator_name: default

# TrainingArguments
TrainingArguments:
  report_to: none
  run_name: cm_test
  output_dir: output
  learning_rate: 3e-5
  do_train: False
  do_eval: False
  do_predict: False
  evaluation_strategy: epoch
  save_strategy: epoch
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  num_train_epochs: 1
  # eval_steps: 100
  # save_steps: 100
  save_total_limit: 5
  fp16: True
  weight_decay: 0.01
  warmup_steps: 100
  load_best_model_at_end: True
  metric_for_best_model: micro_f1
  logging_dir: logs
  lr_scheduler_type: linear

# Model Arguments
ModelingArguments:
  architectures: AutoModelForSequenceClassification
  model_name_or_path: klue/roberta-large
  model_cache_dir: cache

# Project Arguments
ProjectArguments:
  do_analysis: True
  task: klue_re
  wandb_project: klue_re_daeung
  save_model_dir: best
  submit_dir: prediction
  checkpoint: /opt/ml/klue_dir/roberta-large-second