# Data Arguments
DataArguments:
  name: jinmang2/load_klue_re
  revision: v3.0.1b
  data_cache_dir: cache
  prep_pipeline_name: entity_tagging_embedding
  collator_name: entity_embedding

# TrainingArguments
TrainingArguments:
  trainer_class: default
  report_to: wandb  #wandb report
  run_name: entity_embedding_bert
  output_dir: output
  learning_rate: 3e-5
  do_train: True
  do_eval: True
  do_predict: True
  evaluation_strategy: epoch
  # save_strategy: epoch
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  overwrite_output_dir: True
  num_train_epochs: 1
  # eval_steps: 100
  # save_steps: 100
  save_total_limit: 1
  fp16: True
  weight_decay: 0.01
  warmup_steps: 0
  # load_best_model_at_end: True
  # metric_for_best_model: micro_f1
  logging_dir: logs
  logging_strategy: steps
  logging_steps: 500
  lr_scheduler_type: linear
  skip_memory_metrics: True


# Model Arguments
ModelingArguments:
  architectures: BertForSequenceClassificationWithEntity
  # architectures: AutoModelForSequenceClassification
  # model_name_or_path: klue/roberta-large
  model_name_or_path: klue/bert-base
  model_cache_dir: cache

# Project Arguments
ProjectArguments:
  task: klue_re_entity_embedding
  wandb_project: klue_re
  save_model_dir: best
  checkpoint: None
