# Data Arguments
DataArguments:
  name: jinmang2/load_klue_re
  revision: v3.0.0b
  data_cache_dir: cache
  collator_name: default

# TrainingArguments
TrainingArguments:
  report_to: none
  run_name: hps_test
  output_dir: output
  learning_rate: 3e-5
  do_train: True
  do_eval: True
  do_predict: False
  evaluation_strategy: epoch
  # save_strategy: epoch
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  overwrite_output_dir: True
  # num_train_epochs: 1
  # eval_steps: 100
  # save_steps: 100
  save_total_limit: 1
  fp16: True
  weight_decay: 0.01
  warmup_steps: 0
  # load_best_model_at_end: True
  # metric_for_best_model: micro_f1
  logging_dir: logs
  logging_strategy: steps
  logging_steps: 500
  lr_scheduler_type: linear
  skip_memory_metrics: True


# Model Arguments
ModelingArguments:
  architectures: AutoModelForSequenceClassification
  model_name_or_path: klue/roberta-large
  model_cache_dir: cache

# Project Arguments
ProjectArguments:
  task: klue_re
  wandb_project: klue_re
  save_model_dir: best
  submit_dir: prediction
  checkpoint: None

# Hyperparameter Search Arguments
HPSearchArguments:
  smoke_test: False
  ray_address: None
  server_address: None
  method: ASHA
  backend: optuna
  num_samples: 2
  save_ckpt: False
  objective_metric: eval_micro_f1
  hp_per_device_train_batch_size: [16, 32, 64]
  hp_per_device_eval_batch_size: 32
  hp_learning_rate: [3e-5, 5e-5]
  hp_warmup_ratio: [0.0]
  hp_num_train_epochs: [2, 3]
  hp_weight_decay: [0.01]
