# Data Arguments
DataArguments:
  name: jinmang2/load_klue_re
  revision: v2.0.1z
  data_cache_dir: cache
  collator_name: recent
  prep_pipeline_name: recent_entity_tagging

# TrainingArguments
TrainingArguments:
  report_to: wandb
  run_name: recent_tapt
  output_dir: output
  learning_rate: 3e-5
  do_train: True
  do_eval: True
  do_predict: True
  evaluation_strategy: epoch
  save_strategy: epoch
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  num_train_epochs: 10
  # eval_steps: 100
  # save_steps: 100
  save_total_limit: 3
  fp16: True
  weight_decay: 0.01
  warmup_steps: 0
  load_best_model_at_end: True
  metric_for_best_model: micro_f1
  logging_dir: logs
  lr_scheduler_type: linear
  remove_unused_columns: False

# Model Arguments
ModelingArguments:
  architectures: RobertaForKlueRecent
  model_name_or_path: jinmang2/roberta-large-re-tapt-20300
  model_cache_dir: cache
  model_init: recent
  dense_type: Linear
  act_type: tanh

# Project Arguments
ProjectArguments:
  task: recent
  wandb_project: klue_re
  save_model_dir: recent_tapt
  checkpoint: None
  infer_pipeline_name: basic